#ifndef CONSTANTES_DECLARED
#define CONSTANTES_DECLARED
#define MAX_CHARACTERES_NOME_ALUNO 50
#define MAX_CHARACTERES_TURNO_ALUNO 4
#define MAX_CHARACTERES_RESPOSTA_RESPOSTA 60
#define NUMERO_RESPOSTAS_PERGUNTA 4
#define MAX_ALUNOS 20
#define FUNCAUX_MAX_STRING 50
#endif