#ifndef CONSTANTES_DECLARED
#define CONSTANTES_DECLARED

#define MAX_CHARACTERES_NOME_ALUNO 50
#define MAX_CHARACTERES_TURNO_ALUNO 4

#define MAX_CHARACTERES_RESPOSTA_RESPOSTA 60
#define NUMERO_RESPOSTAS_PERGUNTA 4

#define MAX_ALUNOS 20
#define MAX_PERGUNTAS 40
#define FUNCAUX_MAX_STRING 50

const char HEADER_FICHEIROSIO[8]= "INI\0\0\0\0";
const char PERGUNTASC_FICHEIROSIO[8]= "PER\0\0\0\0";
const char ESTUDANTESC_FICHEIROSIO[8]= "EST\0\0\0\0";
const char TREINOSC_FICHEIROSIO[8]= "TRE\0\0\0\0";
const char ENDC_FICHEIROSIO[8]= "END\0\0\0\0";
#endif
